baseURL: 'https://ehri.be/'
languageCode: en-gb
title: Belgium
theme: ehri-nn
copyright: '© 2010-{year} EHRI Consortium.'
defaultContentLanguage: en
dateFormat: '2 January 2006'
summaryLength: 40
params:
  titleShort: EHRI-BE
  facebookUrl: 'https://facebook.com/EHRIproject'
  twitterUrl: 'https://twitter.com/EHRIproject'
  linkedinUrl: 'https://www.linkedin.com/company/ehri-european-holocaust-research-infrastructure'
  blueskyUrl: 'https://bsky.app/profile/ehri-project.eu'

  # `contactName` and `contactEmail` are used to populate the contact page.
  contactName: EHRI-BE
  contactEmail: ehri.belgium@gmail.com

  # `contactForm` is a boolean that determines whether the contact form should be shown.
  contactForm: true

  # `contactFormUrl` is the POST action of the form that will be used to send the contact email.
  contactFormUrl: https://api.staticforms.xyz/submit

  # `funders` is a list of funding bodies, each with a name, logo and an optional URL.
  # If the URL is not provided, the logo will not be linked. The logo should be in the
  # `static/images` folder.
  funders:
    - name: EHRI is funded by the European Commission
      logo: 'eu-logo.svg'
      url: 'https://ec.europa.eu/info/departments/research-and-innovation_en'
  meta:
    title: "EHRI-BE"
    image: images/ehri-logo-large.png
    description: >-
      EHRI-BE is the national node representing Belgium within the European Holocaust Research Infrastructure (EHRI), composed of different institutions located in Belgium with expertise in Holocaust documentation, research, commemoration and education at the different levels of the Belgian federal state.

markup:
  # Configure syntax highlighting for the examples on the `training` page
  highlight:
    style: xcode
  # Since we control the content, it's okay (and useful) to render raw HTML in the markdown
  goldmark:
    renderer:
      unsafe: true

# Configure taxonomy terms
taxonomies:
  - name: category
    weight: 1
  - name: tag
    weight: 2

# Menu configuration. Labels are in the i18n folders:
menu:
  main:
    - identifier: about
      pageRef: about
      weight: 20
    - identifier: partners
      pageRef: partners
      weight: 30
    # - identifier: fellowships_training
    #   pageRef: training
    #   weight: 40
    - identifier: services
      pageRef: services
      weight: 40
    - identifier: services-belgium
      pageRef: services-belgium
      weight: 50
    - identifier: news
      pageRef: news
      weight: 60
    - identifier: contact
      pageRef: contact
      weight: 70
  footer:
    - identifier: about
      pageRef: about
      weight: 20
    - identifier: partners
      pageRef: partners
      weight: 30
    - identifier: fellowships_training
      pageRef: training
      weight: 40
  services:
    - identifier: portal
      pageRef: 'https://portal.ehri-project.eu/'
      weight: 10
    - identifier: document_blog
      pageRef: 'https://blog.ehri-project.eu/'
      weight: 20
    - identifier: digital_tools_guide
      pageRef: 'https://github.com/EHRI/ehri-data-analysis-tools'
      weight: 30
    - identifier: podcast
      pageRef: 'https://www.ehri-project.eu/ehri-podcast-for-the-living-and-the-dead'
      weight: 40


# Language overrides for menu config. TODO: figure out
# how not to duplicate things in e.g. the services menu
languages:
  en:
    title: Belgium
    weight: 1
    languageName: English
  nl: 
    title: België
    weight: 2
    languageName: Dutch
    menu:
      main:
        - identifier: about
          pageRef: about
          weight: 20
        - identifier: partners
          pageRef: partners
          weight: 30
        - identifier: services
          pageRef: services
          weight: 40
        - identifier: services-belgium
          pageRef: services-belgium
          weight: 50
        - identifier: news
          pageRef: news
          weight: 60
        - identifier: contact
          pageRef: contact
          weight: 70
      services:
        - identifier: document_blog
          pageRef: 'https://blog.ehri-project.eu/'
          weight: 20
        - identifier: digital_tools_guide
          pageRef: 'https://github.com/EHRI/ehri-data-analysis-tools'
          weight: 30
        - identifier: podcast
          pageRef: 'https://www.ehri-project.eu/ehri-podcast-for-the-living-and-the-dead'
          weight: 40
      footer:
        - identifier: about
          pageRef: about
          weight: 20
        - identifier: partners
          pageRef: partners
          weight: 30
        - identifier: fellowships_training
          pageRef: training
          weight: 40
  fr:
      title: Belgique
      weight: 3
      languageName: French
      menu:
        main:
          - identifier: about
            pageRef: about
            weight: 20
          - identifier: partners
            pageRef: partners
            weight: 30
          - identifier: services
            pageRef: services
            weight: 40
          - identifier: services-belgium
            pageRef: services-belgium
            weight: 50
          - identifier: news
            pageRef: news
            weight: 60
          - identifier: contact
            pageRef: contact
            weight: 70
        services:
          - identifier: document_blog
            pageRef: 'https://blog.ehri-project.eu/'
            weight: 20
          - identifier: digital_tools_guide
            pageRef: 'https://github.com/EHRI/ehri-data-analysis-tools'
            weight: 30
          - identifier: podcast
            pageRef: 'https://www.ehri-project.eu/ehri-podcast-for-the-living-and-the-dead'
            weight: 40
        footer:
          - identifier: about
            pageRef: about
            weight: 20
          - identifier: partners
            pageRef: partners
            weight: 30
          - identifier: fellowships_training
            pageRef: training
            weight: 40
  de:
    title: Belgien
    weight: 4
    languageName: German
    menu:
      main:
        - identifier: about
          pageRef: about
          weight: 20
        - identifier: partners
          pageRef: partners
          weight: 30
        - identifier: services
          pageRef: services
          weight: 40
        - identifier: services-belgium
          pageRef: services-belgium
          weight: 50
        - identifier: news
          pageRef: news
          weight: 60
        - identifier: contact
          pageRef: contact
          weight: 70
      services:
        - identifier: document_blog
          pageRef: 'https://blog.ehri-project.eu/'
          weight: 20
        - identifier: digital_tools_guide
          pageRef: 'https://github.com/EHRI/ehri-data-analysis-tools'
          weight: 30
        - identifier: podcast
          pageRef: 'https://www.ehri-project.eu/ehri-podcast-for-the-living-and-the-dead'
          weight: 40
      footer:
        - identifier: about
          pageRef: about
          weight: 20
        - identifier: partners
          pageRef: partners
          weight: 30
        - identifier: fellowships_training
          pageRef: training
          weight: 40
